/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRESENTACION;

import DATOS.Consultas;
import NEGOCIACIONES.EMAIL;
import NEGOCIACIONES.QR;
import com.google.zxing.NotFoundException;
import com.google.zxing.WriterException;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.ByteArrayOutputStream;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Cris
 */
public class CRUD extends javax.swing.JFrame {
    JFileChooser file = null;
    Image newImg;
    Consultas CT = new Consultas();
    ArrayList<String> superpowers = new  ArrayList<>();
    ArrayList<Boolean> values = new  ArrayList<>();  
    ArrayList<String[]> info = new ArrayList<>();
    ArrayList<String> SPHRS;
    BufferedImage imagen;
    String sh = "";
    Image imgx;
    File imageDAta = null;
    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
        load();
    }

    private void load() {        
        CboXSel.removeAllItems();
        String cond1 = null, cond2 = null;
        if (RbAH.isSelected()) {
            cond1 = "A";
            cond2 = "E";
        } else if (RbIO.isSelected()) {
            cond1 = "F";
            cond2 = "K";
        } else if (RbPZ.isSelected()) {
            cond1 = "L";
            cond2 = "P";
        } else if (RbOV.isSelected()) {
            cond1 = "Q";
            cond2 = "V";
        }  else if (RbWZ.isSelected()) {
            cond1 = "W";
            cond2 = "Z";
        } 
        SPHRS = new ArrayList();
        SPHRS = CT.getSuperHeroesName(cond1, cond2);
        for (int i = 0; i < SPHRS.size(); i++) {
            String get = SPHRS.get(i);
            CboXSel.addItem(get);
        }
        try {
            loadImg(CT.getImage(sh));
        } catch (Exception e) {
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PlnImg = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        BtnChgImg = new javax.swing.JButton();
        LblName = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        LblAl = new javax.swing.JLabel();
        TxtAl = new javax.swing.JTextField();
        LblPub = new javax.swing.JLabel();
        TxtPub = new javax.swing.JTextField();
        LblGen = new javax.swing.JLabel();
        TxtGeb = new javax.swing.JTextField();
        LblEye = new javax.swing.JLabel();
        TxtEye = new javax.swing.JTextField();
        LblCHar = new javax.swing.JLabel();
        TxtCHar = new javax.swing.JTextField();
        LblRace = new javax.swing.JLabel();
        TxtRace = new javax.swing.JTextField();
        LblSCol = new javax.swing.JLabel();
        TxtSCol = new javax.swing.JTextField();
        LblWe = new javax.swing.JLabel();
        TxtWe = new javax.swing.JTextField();
        LblHei = new javax.swing.JLabel();
        TxtHei = new javax.swing.JTextField();
        LblSuper = new javax.swing.JLabel();
        BtnEmail = new javax.swing.JButton();
        CboXSel = new javax.swing.JComboBox<>();
        LblNamez = new javax.swing.JLabel();
        RbAH = new javax.swing.JRadioButton();
        RbIO = new javax.swing.JRadioButton();
        RbPZ = new javax.swing.JRadioButton();
        BtnUpdate = new javax.swing.JButton();
        RbOV = new javax.swing.JRadioButton();
        RbWZ = new javax.swing.JRadioButton();
        MnBar = new javax.swing.JMenuBar();
        Mn = new javax.swing.JMenu();
        MnHC = new javax.swing.JMenuItem();
        Mn10Height = new javax.swing.JMenuItem();
        Mn10P = new javax.swing.JMenuItem();
        MnBar2 = new javax.swing.JMenu();
        MnPub = new javax.swing.JMenuItem();
        MnSkinColor = new javax.swing.JMenuItem();
        MnDG = new javax.swing.JMenuItem();
        MnAF = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PlnImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PlnImgLayout = new javax.swing.GroupLayout(PlnImg);
        PlnImg.setLayout(PlnImgLayout);
        PlnImgLayout.setHorizontalGroup(
            PlnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PlnImgLayout.setVerticalGroup(
            PlnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        BtnChgImg.setText("Cambiar Imagen");
        BtnChgImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChgImgActionPerformed(evt);
            }
        });

        LblName.setText("Nombre:");

        TxtName.setText("jTextField1");

        LblAl.setText("Alineacion");

        TxtAl.setText("jTextField1");

        LblPub.setText("Editorial");

        TxtPub.setText("jTextField1");

        LblGen.setText("Genero");

        TxtGeb.setText("jTextField1");

        LblEye.setText("Color de Ojos");

        TxtEye.setText("jTextField1");

        LblCHar.setText("Color de Cabello");

        TxtCHar.setText("jTextField1");

        LblRace.setText("Raza");

        TxtRace.setText("jTextField1");

        LblSCol.setText("Color de Piel");

        TxtSCol.setText("jTextField1");

        LblWe.setText("Peso");

        TxtWe.setText("jTextField1");

        LblHei.setText("Altura");

        TxtHei.setText("jTextField1");

        LblSuper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblSuper.setText("Super Poderes");

        BtnEmail.setText("Enviar Informacion");
        BtnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmailActionPerformed(evt);
            }
        });

        CboXSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboXSelActionPerformed(evt);
            }
        });

        LblNamez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNamez.setText("Personaje");

        buttonGroup1.add(RbAH);
        RbAH.setSelected(true);
        RbAH.setText("A-E");
        RbAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAHActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbIO);
        RbIO.setText("F-K");
        RbIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbIOActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbPZ);
        RbPZ.setText("L-P");
        RbPZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbPZActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Actualizar");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbOV);
        RbOV.setText("Q-V");
        RbOV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbOVActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbWZ);
        RbWZ.setText("W-Z");
        RbWZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbWZActionPerformed(evt);
            }
        });

        Mn.setText("Inicio");

        MnHC.setText("Heroes Calvos");
        MnHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHCActionPerformed(evt);
            }
        });
        Mn.add(MnHC);

        Mn10Height.setText("Top 10 Altura");
        Mn10Height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn10HeightActionPerformed(evt);
            }
        });
        Mn.add(Mn10Height);

        Mn10P.setText("Top 10 Poderes");
        Mn10P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn10PActionPerformed(evt);
            }
        });
        Mn.add(Mn10P);

        MnBar.add(Mn);

        MnBar2.setText("Estadisticas");

        MnPub.setText("Editoriales");
        MnPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPubActionPerformed(evt);
            }
        });
        MnBar2.add(MnPub);

        MnSkinColor.setText("Color de Piel");
        MnSkinColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSkinColorActionPerformed(evt);
            }
        });
        MnBar2.add(MnSkinColor);

        MnDG.setText("Distribucion por Genero");
        MnDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDGActionPerformed(evt);
            }
        });
        MnBar2.add(MnDG);

        MnAF.setText("Alineacion Femenina");
        MnAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAFActionPerformed(evt);
            }
        });
        MnBar2.add(MnAF);

        jMenuItem1.setText("Genero por Altura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnBar2.add(jMenuItem1);

        MnBar.add(MnBar2);

        setJMenuBar(MnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtEye)
                                    .addComponent(LblEye, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtCHar)
                                    .addComponent(LblCHar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtSCol, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblSCol, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtRace, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblRace, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtWe)
                                    .addComponent(LblWe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtHei)
                                    .addComponent(LblHei, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnChgImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlnImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(LblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtGeb)
                                    .addComponent(LblGen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtAl)
                                    .addComponent(LblAl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtPub)
                                    .addComponent(LblPub, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblNamez, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CboXSel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RbAH)
                                .addGap(18, 18, 18)
                                .addComponent(RbOV))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RbIO)
                                .addGap(18, 18, 18)
                                .addComponent(RbWZ))
                            .addComponent(RbPZ))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1029, Short.MAX_VALUE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNamez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CboXSel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RbAH)
                            .addComponent(RbOV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RbIO)
                            .addComponent(RbWZ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbPZ)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblAl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtAl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblPub, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtPub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblGen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtGeb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlnImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(BtnChgImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblHei, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtHei, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblRace, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtRace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LblSCol, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtSCol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LblWe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtWe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblEye, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEye, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LblCHar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCHar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(BtnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(312, Short.MAX_VALUE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(167, 167, 167)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnChgImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChgImgActionPerformed
        file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "png");
        file.setFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION){
            try {
                ImageToByte(file.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                loadImg(ImageToByte(file.getSelectedFile()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File selected");
            file = null;
        }
    }//GEN-LAST:event_BtnChgImgActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        String[] info1 = {"name","gender","eyecolor","race","haircolor","height","publisher","skincolor","alignment", "weight"};
        String[] info2 = {TxtName.getText(),TxtGeb.getText(),TxtEye.getText(),TxtRace.getText(),TxtCHar.getText(),TxtHei.getText(),TxtPub.getText(),TxtSCol.getText(),TxtAl.getText(),TxtWe.getText()};
        try {
            CT.UPDATE_HERO(info1, info2, sh, "superheroes", "name");
            String[] data = getDataTable(superpowers.size());
            CT.UPDATE_HERO(superpowers.toArray(new String[0]), data, sh, "superpowers", "hero_names");
            
            JOptionPane.showMessageDialog(null, "Se ha actualizado la informacion con exito!","Actualizado!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e);
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "No se ha podido actualizar","Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            InsImg();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void RbPZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbPZActionPerformed
        load();
    }//GEN-LAST:event_RbPZActionPerformed

    private void RbIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbIOActionPerformed
        load();
    }//GEN-LAST:event_RbIOActionPerformed

    private void RbAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAHActionPerformed
        load();
    }//GEN-LAST:event_RbAHActionPerformed

    private void CboXSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboXSelActionPerformed
        imageDAta = null;
        jTable1.removeAll();
        try {
            sh = CboXSel.getSelectedItem().toString();
            System.out.println(sh);
            info = CT.getSuperHeroesInfo(sh);
            TxtName.setText(info.get(0)[0]);///
            TxtGeb.setText(info.get(0)[1]);///
            TxtEye.setText(info.get(0)[2]);///
            TxtRace.setText(info.get(0)[3]);///
            TxtCHar.setText(info.get(0)[4]);
            TxtHei.setText(info.get(0)[5]);//
            TxtPub.setText(info.get(0)[6]);///
            TxtSCol.setText(info.get(0)[7]);
            TxtAl.setText(info.get(0)[8]);//
            TxtWe.setText(info.get(0)[9]);//

            superpowers = CT.loadSuperPowers();
            values = CT.getPowersInfo(sh, superpowers.size());

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Superpoderess", superpowers.toArray(new String[0]));
            model.addColumn("Posee", values.toArray(new Boolean[0]));

            jTable1.setModel(model);
            jTable1.getColumnModel().getColumn(1).setCellEditor(jTable1.getDefaultEditor(Boolean.class));
            jTable1.getColumnModel().getColumn(1).setCellRenderer(jTable1.getDefaultRenderer(Boolean.class));
            loadImg(CT.getImage(sh));
        } catch (Exception e) {
            System.out.println(e);
            System.out.println(e.getMessage());
        }
        if (CT.getImage(sh) == null){
            lblImg.setIcon(null);
            lblImg.revalidate();
        }

    }//GEN-LAST:event_CboXSelActionPerformed

    private void BtnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmailActionPerformed
        String listaPD = "";
        for (int i = 0; i < values.size(); i++) {
            Boolean get = values.get(i);
            if (get == true) {
                listaPD =  listaPD + " -"+superpowers.get(i) + "\n";
            }

        }
        String psInfo = "Informacion: \nNombre: " + info.get(0)[0] + "\n" +
        "Genero: " + info.get(0)[1] + "\n" +
        "Color de Ojos: "+info.get(0)[2]+ "\n" +
        "Raza: "+info.get(0)[3]+ "\n" +
        "Color de Cabello: "+info.get(0)[4]+ "\n" +
        "Altura: "+info.get(0)[5]+ "\n" +
        "Editorial: "+info.get(0)[6]+ "\n" +
        "Color de Piel: "+info.get(0)[7]+ "\n" +
        "Alineacion: "+info.get(0)[8]+ "\n" +
        "Peso: "+info.get(0)[9]+ "\n";
        EMAIL msm = new EMAIL();
        QR gqr = new QR();
        File qr = null;
        try {
            qr = gqr.DFCRQR(psInfo + "\nLista de Poderes: \n" + listaPD);
        } catch (WriterException ex) {
            Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotFoundException ex) {
            Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(imageDAta != null){
                 msm.EnviarCorreo(qr, imageDAta);
            } else {
                msm.EnviarCorreo(qr); 
            }
           
        } catch (IOException ex) {
            Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
        imageDAta = null;
    }//GEN-LAST:event_BtnEmailActionPerformed

    private void MnHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHCActionPerformed
        GraficosListas GFL = new GraficosListas("Super Heroes Calvos", CT.obtenerLHNH(), CT.obtenerSHWNH());
        GFL.setVisible(true);
        GFL.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnHCActionPerformed

    private void Mn10HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn10HeightActionPerformed
        String[] Columnas = {"Nombre", "Genero", "Color de Ojos", "Raza", "Color de Cabello", "Altura", "Editorial"};
        Tabla TB = new Tabla(CT.obtenerHSH(), Columnas);
        TB.setVisible(true);
        TB.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Mn10HeightActionPerformed

    private void Mn10PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn10PActionPerformed
        GraficosRBTNListas GRBL = new GraficosRBTNListas(CT.loadPublisher2(), "Top 10 Super Heroes con mas Super Poderes");
        GRBL.setLocationRelativeTo(null);
        GRBL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Mn10PActionPerformed

    private void MnPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPubActionPerformed

        Graficos GF = new Graficos("Porcentaje de Publishers",   CT.loadPublisher());
        GF.setVisible(true);
        GF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnPubActionPerformed

    private void MnSkinColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSkinColorActionPerformed
        Graficos GF = new Graficos("Porcentaje de Heroes por Color",  CT.obtenerSKN());
        GF.setVisible(true);
        GF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnSkinColorActionPerformed

    private void MnDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDGActionPerformed
        Graficos DG = new Graficos("Porcentaje de Generos",   CT.loadGender());
        DG.setVisible(true);
        DG.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnDGActionPerformed

    private void MnAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAFActionPerformed
        Graficos AF = new Graficos("Porcentaje de Alineación Femenina",   CT.loadposfem());
        AF.setVisible(true);
        AF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnAFActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //        String[] Columnas = {"Altura", "Genero"};
        ArrayList<String> AL = new ArrayList<>();
        AL.add("Male");
        AL.add("Female");
        AL.add("-");
        GraficosRBTNListas HG = new GraficosRBTNListas(AL, "Altura Genero");
        //Graficos HG = new Graficos("Porcentaje de Altura por Género", CT.loadheigen());
        HG.setVisible(true);
        HG.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void RbOVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbOVActionPerformed
        load();
    }//GEN-LAST:event_RbOVActionPerformed

    private void RbWZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbWZActionPerformed
       load();
    }//GEN-LAST:event_RbWZActionPerformed
    private void InsImg() throws FileNotFoundException{
        CT.addImage(ImageToByte(file.getSelectedFile()), sh);
    }        
    public Image ResizeImage(Image Imagez){
            Image img = Imagez;
            Image newImg = img.getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
            return newImg;
        }
    
    public ImageIcon IconImage(Image newImg) {
        ImageIcon image = new ImageIcon(newImg);
            return image;
    }
        private byte [] ImageToByte(File file) throws FileNotFoundException{
        FileInputStream fis = new FileInputStream(file);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        try {
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);     
            }
        } catch (IOException ex) {
        }
        byte[] bytez = bos.toByteArray(); 
     return bytez;
    } 
        public void loadImg(byte[] image) throws IOException{
        imgx = Toolkit.getDefaultToolkit().createImage(image);
        lblImg.setIcon(IconImage(ResizeImage(imgx))); 
        imageDAta = new File("Hero.png");
        try (OutputStream stream = new FileOutputStream("Hero.png")) {
            stream.write(image);
        }
        }
    private String[] getDataTable(int size){
        String[] poderes = new String[size];
        System.out.println(jTable1.getRowCount());
        for(int i = 0; i < (jTable1.getRowCount()); i++) {
            poderes[i] = Boolean.toString((boolean) jTable1.getValueAt(i, 1));
        }
        
        return poderes;
        
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnChgImg;
    private javax.swing.JButton BtnEmail;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CboXSel;
    private javax.swing.JLabel LblAl;
    private javax.swing.JLabel LblCHar;
    private javax.swing.JLabel LblEye;
    private javax.swing.JLabel LblGen;
    private javax.swing.JLabel LblHei;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblNamez;
    private javax.swing.JLabel LblPub;
    private javax.swing.JLabel LblRace;
    private javax.swing.JLabel LblSCol;
    private javax.swing.JLabel LblSuper;
    private javax.swing.JLabel LblWe;
    private javax.swing.JMenu Mn;
    private javax.swing.JMenuItem Mn10Height;
    private javax.swing.JMenuItem Mn10P;
    private javax.swing.JMenuItem MnAF;
    private javax.swing.JMenuBar MnBar;
    private javax.swing.JMenu MnBar2;
    private javax.swing.JMenuItem MnDG;
    private javax.swing.JMenuItem MnHC;
    private javax.swing.JMenuItem MnPub;
    private javax.swing.JMenuItem MnSkinColor;
    private javax.swing.JPanel PlnImg;
    private javax.swing.JRadioButton RbAH;
    private javax.swing.JRadioButton RbIO;
    private javax.swing.JRadioButton RbOV;
    private javax.swing.JRadioButton RbPZ;
    private javax.swing.JRadioButton RbWZ;
    private javax.swing.JTextField TxtAl;
    private javax.swing.JTextField TxtCHar;
    private javax.swing.JTextField TxtEye;
    private javax.swing.JTextField TxtGeb;
    private javax.swing.JTextField TxtHei;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPub;
    private javax.swing.JTextField TxtRace;
    private javax.swing.JTextField TxtSCol;
    private javax.swing.JTextField TxtWe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblImg;
    // End of variables declaration//GEN-END:variables
}
