/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRESENTACION;

import DATOS.Consultas;
import NEGOCIACIONES.PieNGS;
import OBJETOs.PieChart;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JRadioButton;

/**
 *
 * @author Cris
 */
public class GraficosRBTNListas extends javax.swing.JFrame {
    int tamZ;
ArrayList<JRadioButton> botones = new ArrayList<JRadioButton>();
String Titulo = "";
Consultas CT = new Consultas();
    PieNGS pie = new PieNGS();
    /**
     * Creates new form GraficosRBTNListas
     */
    public GraficosRBTNListas() {
        initComponents();
    }
    
    public GraficosRBTNListas(ArrayList<String> editoriales, String Titulo) {
        initComponents();
        CrearRBTN(editoriales);
        this.Titulo = Titulo;
        if (Titulo.equals("Altura Genero")){
            List.setEnabled(false);
            LblTitle.setVisible(false);
            jScrollPane1.setVisible(false);
            List.setVisible(false);
             System.out.println(Titulo);
        }
    }
    
    private void CrearRBTN(ArrayList<String> EDT) {       
        PlnRB.setLayout(new GridLayout(EDT.size()/2, EDT.size()/2));  
        int z = 0;
        for (int i = 0; i < EDT.size(); i++) {
            String get = EDT.get(i);
            if (get == null ) {
                get = "Desconocido";
            } else if (get.equals("-")){
                get = "Género Desconocido";
            } else if (get.equals("Female")){
                get = "Mujer";
            } else if (get.equals("Male")){
                get = "Hombre";
            }
            JRadioButton boton = new JRadioButton();
            if (z == 0){
            boton.setSelected(true);
            boton.setText(get);
            buttonGroup1.add(boton);
            botones.add(boton);
        }
            boton.setText(get);
            buttonGroup1.add(boton);
            botones.add(boton);       
        }
        for (int i = 0; i < botones.size(); i++) {
            JRadioButton get = botones.get(i);
            PlnRB.add(get);
            //jPanel2.validate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        LblTitle = new javax.swing.JLabel();
        PlnPie = new javax.swing.JPanel();
        PlnRB = new javax.swing.JPanel();
        LblHeader = new javax.swing.JLabel();
        BtnVis = new javax.swing.JButton();
        D50 = new javax.swing.JLabel();
        D70 = new javax.swing.JLabel();
        D71 = new javax.swing.JLabel();
        MnBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1550, 600));
        setSize(new java.awt.Dimension(1550, 488));
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(List);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(655, 89, 258, 376);

        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LblTitle);
        LblTitle.setBounds(655, 6, 254, 57);

        javax.swing.GroupLayout PlnPieLayout = new javax.swing.GroupLayout(PlnPie);
        PlnPie.setLayout(PlnPieLayout);
        PlnPieLayout.setHorizontalGroup(
            PlnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        PlnPieLayout.setVerticalGroup(
            PlnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(PlnPie);
        PlnPie.setBounds(931, 6, 591, 459);

        javax.swing.GroupLayout PlnRBLayout = new javax.swing.GroupLayout(PlnRB);
        PlnRB.setLayout(PlnRBLayout);
        PlnRBLayout.setHorizontalGroup(
            PlnRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PlnRBLayout.setVerticalGroup(
            PlnRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(PlnRB);
        PlnRB.setBounds(6, 89, 508, 376);

        LblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHeader.setText("Editoriales");
        getContentPane().add(LblHeader);
        LblHeader.setBounds(6, 6, 508, 65);

        BtnVis.setText("Visualizar");
        BtnVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVisActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVis);
        BtnVis.setBounds(545, 198, 100, 50);
        getContentPane().add(D50);
        D50.setBounds(660, 100, 410, 16);
        getContentPane().add(D70);
        D70.setBounds(660, 180, 410, 16);
        getContentPane().add(D71);
        D71.setBounds(660, 140, 410, 16);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MnBar.add(jMenu1);

        setJMenuBar(MnBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Menu main = new Menu();
        main.setVisible(true);        
        main.setLocationRelativeTo(null);
        this.dispose();      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVisActionPerformed
        PlnPie.removeAll();
        PlnPie.validate();
        String publi = getPublisher();    
        if (Titulo.equals("Altura Genero")){
            if (publi.equals("Hombre")){
                publi = "Male";
            } else if (publi.equals("Mujer")){
                publi = "Female";
            } else if (publi.equals("Género Desconocido")){
                publi = "-";
        
        }
        calTam(CT.loadheigen(publi));
        AltD(CT.loadAltD(publi));
        Alt170(CT.loadAlt170(publi));
        AltR(CT.loadAltR(publi));
        CrearGraficoX(Titulo, CT.loadheigen(publi));        
        }else 
        CrearGraficos(Titulo, CT.obtenerEstPoderes(publi));
        LlenarLista(CT.obtenerEstPoderes(publi), Titulo); 

    }//GEN-LAST:event_BtnVisActionPerformed
    
    private void AltD(ArrayList<String> alt){
        int tamX = alt.size();
        System.out.println(tamX);
        double per = ((tamX * 100)/tamZ); 
        D50.setText("De Altura Desconocida " + per + "%");
    }
    private void Alt170(ArrayList<String> alt){
        int tamX = alt.size();
        System.out.println(tamX);
        double per = ((tamX * 100)/tamZ); 
        D71.setText("De 62.5 a 170 cm " + per + "%");
    }
    private void AltR(ArrayList<String> alt){
        int tamX = alt.size();
        System.out.println(tamX);
        double per = ((tamX * 100)/tamZ); 
        D70.setText("De 173 a 975 cm " + per + "%");
    }
    private void calTam(ArrayList<String[]> alt){
        tamZ = alt.size();
        System.out.println(tamZ);
    }
            
    private void LlenarLista(ArrayList<String[]> array, String titulo) {
        
        LblTitle.setText("Lista de " + titulo);
         DefaultListModel<String> model = new DefaultListModel<>();
         for (int i = 0; i < array.size(); i++) {
            String get = array.get(i)[0];
             model.addElement(get);
        }
         List.setModel(model);
         
    }
  
     private void CrearGraficos(String Titulo, ArrayList<String[]> data) { 
        try {           
            PieChart CC = new PieChart("Gráfico", Titulo, pie.createDataset3(data), PlnPie);
        } catch (FileNotFoundException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
     private void CrearGraficoX(String Titulo, ArrayList<String[]> data) { 
        try {           
            PieChart CC = new PieChart("Gráfico", Titulo, pie.createDatasetX(data), PlnPie);
        } catch (FileNotFoundException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    private String getPublisher() {
        for (int i = 0; i < botones.size(); i++) {
            JRadioButton get = botones.get(i);
            if (get.isSelected()){
                return get.getText();
            }
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficosRBTNListas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVis;
    private javax.swing.JLabel D50;
    private javax.swing.JLabel D70;
    private javax.swing.JLabel D71;
    private javax.swing.JLabel LblHeader;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JList<String> List;
    private javax.swing.JMenuBar MnBar;
    private javax.swing.JPanel PlnPie;
    private javax.swing.JPanel PlnRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
