/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRESENTACION;

import DATOS.Consultas;
import NEGOCIACIONES.PieNGS;
import OBJETOs.PieChart;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JRadioButton;

/**
 *
 * @author Cris
 */
public class GraficosRBTNListas extends javax.swing.JFrame {
ArrayList<JRadioButton> botones = new ArrayList<JRadioButton>();
String Titulo = "";
Consultas CT = new Consultas();
    PieNGS pie = new PieNGS();
    /**
     * Creates new form GraficosRBTNListas
     */
    public GraficosRBTNListas() {
        initComponents();
    }
    
    public GraficosRBTNListas(ArrayList<String> editoriales, String Titulo) {
        initComponents();
        CrearRBTN(editoriales);
        this.Titulo = Titulo;
    }
    
    private void CrearRBTN(ArrayList<String> EDT) {
         if (Titulo.equals("Altura Genero")){
            List.setEnabled(false);
            LblTitle.setVisible(false);
        
        }
        PlnRB.setLayout(new GridLayout(EDT.size()/2, EDT.size()/2));
        
        for (int i = 0; i < EDT.size(); i++) {
            String get = EDT.get(i);
            if (get == null ) {
                get = "Desconocido";
            } else if (get.equals("-")){
                get = "Género Desconocido";
            } else if (get.equals("Female")){
                get = "Mujer";
            } else if (get.equals("Male")){
                get = "Hombre";
            }
            JRadioButton boton = new JRadioButton();
            boton.setText(get);
            buttonGroup1.add(boton);
            botones.add(boton);
        }
        for (int i = 0; i < botones.size(); i++) {
            JRadioButton get = botones.get(i);
            PlnRB.add(get);
            //jPanel2.validate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        LblTitle = new javax.swing.JLabel();
        PlnPie = new javax.swing.JPanel();
        PlnRB = new javax.swing.JPanel();
        LblHeader = new javax.swing.JLabel();
        BtnVis = new javax.swing.JButton();
        MnBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(List);

        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PlnPieLayout = new javax.swing.GroupLayout(PlnPie);
        PlnPie.setLayout(PlnPieLayout);
        PlnPieLayout.setHorizontalGroup(
            PlnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        PlnPieLayout.setVerticalGroup(
            PlnPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PlnRBLayout = new javax.swing.GroupLayout(PlnRB);
        PlnRB.setLayout(PlnRBLayout);
        PlnRBLayout.setHorizontalGroup(
            PlnRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PlnRBLayout.setVerticalGroup(
            PlnRBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHeader.setText("Editoriales");

        BtnVis.setText("Visualizar");
        BtnVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVisActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        MnBar.add(jMenu1);

        setJMenuBar(MnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlnRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(BtnVis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PlnPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlnPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(PlnRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(BtnVis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Menu main = new Menu();
        main.setVisible(true);        
        main.setLocationRelativeTo(null);
        this.dispose();      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVisActionPerformed
        PlnPie.removeAll();
        PlnPie.validate();
        String publi = getPublisher();    
        if (Titulo.equals("Altura Genero")){
            if (publi.equals("Hombre")){
                publi = "Male";
            } else if (publi.equals("Mujer")){
                publi = "Female";
            } else if (publi.equals("Género Desconocido")){
                publi = "-";
        
        }
        
        CrearGraficoX(Titulo, CT.loadheigen(publi));        
        }else 
        CrearGraficos(Titulo, CT.obtenerEstPoderes(publi));
        LlenarLista(CT.obtenerEstPoderes(publi), Titulo); 

    }//GEN-LAST:event_BtnVisActionPerformed
    
    
    private void LlenarLista(ArrayList<String[]> array, String titulo) {
        
        LblTitle.setText("Lista de " + titulo);
         DefaultListModel<String> model = new DefaultListModel<>();
         for (int i = 0; i < array.size(); i++) {
            String get = array.get(i)[0];
             model.addElement(get);
        }
         List.setModel(model);
         
    }
  
     private void CrearGraficos(String Titulo, ArrayList<String[]> data) { 
        try {           
            PieChart CC = new PieChart("Gráfico", Titulo, pie.createDataset3(data), PlnPie);
        } catch (FileNotFoundException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
     private void CrearGraficoX(String Titulo, ArrayList<String[]> data) { 
        try {           
            PieChart CC = new PieChart("Gráfico", Titulo, pie.createDatasetX(data), PlnPie);
        } catch (FileNotFoundException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    private String getPublisher() {
        for (int i = 0; i < botones.size(); i++) {
            JRadioButton get = botones.get(i);
            if (get.isSelected()){
                return get.getText();
            }
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficosRBTNListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficosRBTNListas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVis;
    private javax.swing.JLabel LblHeader;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JList<String> List;
    private javax.swing.JMenuBar MnBar;
    private javax.swing.JPanel PlnPie;
    private javax.swing.JPanel PlnRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
