/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRESENTACION;

import DATOS.Consultas;
import OBJETOs.PieChart;
import NEGOCIACIONES.PieChartBar;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Cris
 */
public class Menu extends javax.swing.JFrame {
PieChartBar PC = new PieChartBar();
Consultas CT = new Consultas();
    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MnBar = new javax.swing.JMenuBar();
        Mn = new javax.swing.JMenu();
        MnHC = new javax.swing.JMenuItem();
        Mn10Height = new javax.swing.JMenuItem();
        Mn10P = new javax.swing.JMenuItem();
        MnBar2 = new javax.swing.JMenu();
        MnPub = new javax.swing.JMenuItem();
        MnSkinColor = new javax.swing.JMenuItem();
        MnDG = new javax.swing.JMenuItem();
        MnAF = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mn.setText("Inicio");

        MnHC.setText("Heroes Calvos");
        MnHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHCActionPerformed(evt);
            }
        });
        Mn.add(MnHC);

        Mn10Height.setText("Top 10 Altura");
        Mn10Height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn10HeightActionPerformed(evt);
            }
        });
        Mn.add(Mn10Height);

        Mn10P.setText("Top 10 Poderes");
        Mn10P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn10PActionPerformed(evt);
            }
        });
        Mn.add(Mn10P);

        MnBar.add(Mn);

        MnBar2.setText("Estadisticas");

        MnPub.setText("Editoriales");
        MnPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPubActionPerformed(evt);
            }
        });
        MnBar2.add(MnPub);

        MnSkinColor.setText("Color de Piel");
        MnSkinColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSkinColorActionPerformed(evt);
            }
        });
        MnBar2.add(MnSkinColor);

        MnDG.setText("Distribucion por Genero");
        MnDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDGActionPerformed(evt);
            }
        });
        MnBar2.add(MnDG);

        MnAF.setText("Alineacion Femenina");
        MnAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAFActionPerformed(evt);
            }
        });
        MnBar2.add(MnAF);

        jMenuItem1.setText("Genero por Altura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnBar2.add(jMenuItem1);

        MnBar.add(MnBar2);

        setJMenuBar(MnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1157, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnSkinColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSkinColorActionPerformed
        Graficos GF = new Graficos("Porcentaje de Heroes por Color",  CT.obtenerSKN());
        GF.setVisible(true);
        GF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnSkinColorActionPerformed

    private void MnPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPubActionPerformed

        Graficos GF = new Graficos("Porcentaje de Publishers",   CT.loadPublisher());
        GF.setVisible(true);
        GF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnPubActionPerformed

    private void MnHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHCActionPerformed
        GraficosListas GFL = new GraficosListas("Super Heroes Calvos", CT.obtenerLHNH(), CT.obtenerSHWNH());
        GFL.setVisible(true);
        GFL.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnHCActionPerformed

    private void Mn10HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn10HeightActionPerformed
        String[] Columnas = {"Nombre", "Genero", "Color de Ojos", "Raza", "Color de Cabello", "Altura", "Editorial"};    
        Tabla TB = new Tabla(CT.obtenerHSH(), Columnas);
        TB.setVisible(true);
        TB.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Mn10HeightActionPerformed

    private void Mn10PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn10PActionPerformed
       GraficosRBTNListas GRBL = new GraficosRBTNListas(CT.loadPublisher2(), "Top 10 Super Heroes con mas Super Poderes");
       GRBL.setLocationRelativeTo(null);
       GRBL.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Mn10PActionPerformed

    private void MnDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDGActionPerformed
        Graficos DG = new Graficos("Porcentaje de Generos",   CT.loadGender());
        DG.setVisible(true);
        DG.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnDGActionPerformed

    private void MnAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAFActionPerformed
        Graficos AF = new Graficos("Porcentaje de Alineación Femenina",   CT.loadposfem());
        AF.setVisible(true);
        AF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_MnAFActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        String[] Columnas = {"Altura", "Genero"};
        ArrayList<String> AL = new ArrayList<>();
        AL.add("Male");
        AL.add("Female");
        AL.add("-");
        GraficosRBTNListas HG = new GraficosRBTNListas(AL, "Altura Genero");  
        //Graficos HG = new Graficos("Porcentaje de Altura por Género", CT.loadheigen());
        HG.setVisible(true);
        HG.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try{
            UIManager.setLookAndFeel(new FlatAtomOneDarkIJTheme());
        } catch (Exception e){
            e.printStackTrace();
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatAtomOneDarkIJTheme".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mn;
    private javax.swing.JMenuItem Mn10Height;
    private javax.swing.JMenuItem Mn10P;
    private javax.swing.JMenuItem MnAF;
    private javax.swing.JMenuBar MnBar;
    private javax.swing.JMenu MnBar2;
    private javax.swing.JMenuItem MnDG;
    private javax.swing.JMenuItem MnHC;
    private javax.swing.JMenuItem MnPub;
    private javax.swing.JMenuItem MnSkinColor;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
